modLoader = "javafml"
loaderVersion = "[49,)"
license = "Apache 2.0"
issueTrackerURL = "https://github.com/MrJeremyFisher/HealthBar/issues"
[[mods]]
modId = "healthbar"
version = "${version}"
authors = "MrJeremyFisher"
displayName = "HealthBar"
logoFile = "icon.png"

description = "A lightweight and highly configurable health display."

[[dependencies.healthbar]]
modId = "forge"
mandatory = true
versionRange = "[49,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.healthbar]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"
