modLoader = "javafml"
loaderVersion = "[${forge_version},)"
license = "Apache 2.0"
issueTrackerURL = "${issues_url}"

[[mods]]
modId = "healthbar"
version = "${version}"
authors = "MrJeremyFisher"
displayName = "HealthBar"
logoFile = "icon.png"
description = "A lightweight and highly configurable health display."

[[dependencies.healthbar]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.healthbar]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version}]"
ordering = "NONE"
side = "BOTH"
