modLoader = "javafml"
loaderVersion = "[49,)"
license = "Apache 2.0"
issueTrackerURL = "https://jerem/HealthBar/issues"
[[mods]]
modId = "healthbar"
version = "${version}"
displayName = "HealthBar"
logoFile = "icon.png"

description = '''

'''

[[dependencies.healthbar]]
modId = "forge"
mandatory = true
versionRange = "[49,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.healthbar]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"
