modLoader = "javafml"
loaderVersion = "[1,)"
license = "Apache 2.0"
issueTrackerURL = "${issues_url}"

[[mods]]
modId = "healthbar"
version = "${version}"
authors = "MrJeremyFisher"
displayName = "HealthBar"
logoFile = "icon.png"
description = "A lightweight and highly configurable health display."

[[dependencies.healthbar]]
modId = "neoforge"
mandatory = true
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.healthbar]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version}]"
ordering = "NONE"
side = "CLIENT"